# Generated by Django 3.1.2 on 2021-01-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_messagehistory_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='message_length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='message_words',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunSQL('UPDATE db_messagehistory SET message_length=Length(message)')
    ]
