version: '3.3'

services:
  web:
    image:  ghcr.io/cadovvl/bot/cadovvl-bot:latest
    restart: always
    working_dir: /code
    command: python main.py
    volumes:
      - ./db_data/:/db_data/
    env_file:
      - ./.env
    depends_on:
      - migrations

  migrations:
    image:  ghcr.io/cadovvl/bot/cadovvl-bot:latest
    working_dir: /code
    command: python manage.py migrate
    env_file:
      - ./.env
    volumes:
      - ./db_data/:/db_data/
